<?php

use Illuminate\Database\Seeder;

class SeedGalleryVideos extends Seeder {
    public function run() {
        DB::table('gallery_videos')->insert(array(
            ['thumbnail' => "1.jpg",
                'title' => "TESTE 1",
                'desc' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam rutrum massa nec mauris varius elementum. ",
                'video' => "https://www.youtube.com/watch?v=Q0oIoR9mLwc"],
            ['thumbnail' => "1.jpg",
                'title' => "TESTE 1",
                'desc' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam rutrum massa nec mauris varius elementum. ",
                'video' => "https://www.youtube.com/watch?v=Q0oIoR9mLwc"],
            ['thumbnail' => "1.jpg",
                'title' => "TESTE 1",
                'desc' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam rutrum massa nec mauris varius elementum. ",
                'video' => "https://www.youtube.com/watch?v=Q0oIoR9mLwc"],
            ['thumbnail' => "1.jpg",
                'title' => "TESTE 1",
                'desc' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam rutrum massa nec mauris varius elementum. ",
                'video' => "https://www.youtube.com/watch?v=Q0oIoR9mLwc"],
            ['thumbnail' => "1.jpg",
                'title' => "TESTE 1",
                'desc' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam rutrum massa nec mauris varius elementum. ",
                'video' => "https://www.youtube.com/watch?v=Q0oIoR9mLwc"],
            ['thumbnail' => "1.jpg",
                'title' => "TESTE 1",
                'desc' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam rutrum massa nec mauris varius elementum. ",
                'video' => "https://www.youtube.com/watch?v=Q0oIoR9mLwc"],
            ['thumbnail' => "1.jpg",
                'title' => "TESTE 1",
                'desc' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam rutrum massa nec mauris varius elementum. ",
                'video' => "https://www.youtube.com/watch?v=Q0oIoR9mLwc"],
            ['thumbnail' => "1.jpg",
                'title' => "TESTE 1",
                'desc' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam rutrum massa nec mauris varius elementum. ",
                'video' => "https://www.youtube.com/watch?v=Q0oIoR9mLwc"],
            ['thumbnail' => "1.jpg",
                'title' => "TESTE 1",
                'desc' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam rutrum massa nec mauris varius elementum. ",
                'video' => "https://www.youtube.com/watch?v=Q0oIoR9mLwc"],
            ['thumbnail' => "1.jpg",
                'title' => "TESTE 1",
                'desc' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam rutrum massa nec mauris varius elementum. ",
                'video' => "https://www.youtube.com/watch?v=Q0oIoR9mLwc"],
            ['thumbnail' => "1.jpg",
                'title' => "TESTE 1",
                'desc' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam rutrum massa nec mauris varius elementum. ",
                'video' => "https://www.youtube.com/watch?v=Q0oIoR9mLwc"],
            ['thumbnail' => "1.jpg",
                'title' => "TESTE 1",
                'desc' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam rutrum massa nec mauris varius elementum. ",
                'video' => "https://www.youtube.com/watch?v=Q0oIoR9mLwc"],
            ['thumbnail' => "1.jpg",
                'title' => "TESTE 1",
                'desc' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam rutrum massa nec mauris varius elementum. ",
                'video' => "https://www.youtube.com/watch?v=Q0oIoR9mLwc"],
        ));
    }
}
