<?php

use Illuminate\Database\Seeder;

class SeedGalleryPhotos extends Seeder {
    public function run() {
        DB::table('gallery_photos')->insert(array(
            ['thumbnail' => "2-t.jpg",
                'title' => "TESTE 1",
                'photo' => "2.jpg"],
            ['thumbnail' => "2-t.jpg",
                'title' => "TESTE 1",
                'photo' => "2.jpg"],
            ['thumbnail' => "2-t.jpg",
                'title' => "TESTE 1",
                'photo' => "2.jpg"],
            ['thumbnail' => "2-t.jpg",
                'title' => "TESTE 1",
                'photo' => "2.jpg"],
            ['thumbnail' => "2-t.jpg",
                'title' => "TESTE 1",
                'photo' => "2.jpg"],
            ['thumbnail' => "2-t.jpg",
                'title' => "TESTE 1",
                'photo' => "2.jpg"],
            ['thumbnail' => "2-t.jpg",
                'title' => "TESTE 1",
                'photo' => "2.jpg"],
            ['thumbnail' => "2-t.jpg",
                'title' => "TESTE 1",
                'photo' => "2.jpg"],
            ['thumbnail' => "2-t.jpg",
                'title' => "TESTE 1",
                'photo' => "2.jpg"],
            ['thumbnail' => "2-t.jpg",
                'title' => "TESTE 1",
                'photo' => "2.jpg"],
            ['thumbnail' => "2-t.jpg",
                'title' => "TESTE 1",
                'photo' => "2.jpg"],
            ['thumbnail' => "2-t.jpg",
                'title' => "TESTE 1",
                'photo' => "2.jpg"],
            ['thumbnail' => "2-t.jpg",
                'title' => "TESTE 1",
                'photo' => "2.jpg"],
            ['thumbnail' => "2-t.jpg",
                'title' => "TESTE 1",
                'photo' => "2.jpg"],
            ['thumbnail' => "2-t.jpg",
                'title' => "TESTE 1",
                'photo' => "2.jpg"],
            ['thumbnail' => "2-t.jpg",
                'title' => "TESTE 1",
                'photo' => "2.jpg"],
            ['thumbnail' => "2-t.jpg",
                'title' => "TESTE 1",
                'photo' => "2.jpg"],
        ));
    }
}
